### ISSUE TITLE
Member Register

### ISSUE THREAD

**Issue by RicardoVessaro** [RicardoVessaro/aric-backend#4]
### Features
Able to register members. 
Members can login.
Members can logout.
Members can be deactivated.

### Requirements
1. Register members requires following fields:

> 1. Username (unique).
> 2. Name
> 3. E-mail (unique)
> 4. Password

2. Password validations:

> 1. At least 8 characters, including at least one upper case, lower case, number, special character.
> 2. Encrypted

3. Members can be deactivated but not deleted.
4. Use JWT authentications initially.

### TODO

- [X] Register member.
- [X] Authenticate member with JWT.
- [x] Validate required fields.
- [x] Validate unique username.
- [x] Validate unique email.
- [x] Validate password.
- [x] validate email is valid.
